name: Lab4 Add Testing To Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  ci-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - run: npm clean-install

      - name: Run Unit-Tests
        run: npm run lint

      - name: Run Unit-Tests
        run: npm run unit-tests

      - name: Uload the UT coverage
        uses: actions/upload-artifact@v3
        with:
          name: ut-${{ github.sha }}
          path: ./coverage

      - name: Validate Coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          files: coverage-final.json
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          dry_run: true

      - if: github.ref == 'refs/heads/main'
        run: npm pack

      - if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: node-todo-${{ github.sha }}
          path: ./*.tgz
